# command line: main.py recognition -c config/st_gcn.twostream/congreg8-marker/test.yaml

base_lr: 0.01
batch_size: 256
config: config/st_gcn.twostream/congreg8-marker/test.yaml
debug: false
device: 0
eval_interval: 1
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn_twostream.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: congreg8-marker
        strategy: spatial
    in_channels: 3
    num_class: 2
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
start_epoch: 0
step: []
test_batch_size: 64
test_feeder_args:
    data_path: ./data/CongreG8/marker/vr/datavr.npy
    label_path: ./data/CongreG8/marker/vr/labelvr.npy
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: ./work_dir/recognition/congreg8-markers_2/ST_GCN_TWO_STREAM_1/epoch80_model.pt
work_dir: ./work_dir/tmp